//
//routestate = {
//    "/" :[[],[]],
//    "/inbox":[[],[{_id:"FDDp1ru10UCxl2Xnv2NT2Q",route:"/inbox"}]],
//    "/next":[[1],[{_id:"I10ifHO0PEGrSxI_nNi-ag",route:"/next"}]],
//    "/next/today":[[1],[{_id:"I10ifHO0PEGrSxI_nNi-ag",route:"/next"},{_id:"bFolGPm9ikShWzx76mq0GQ",route:"/next/today"}]],
//    "/next/thisweek":[[1],[{_id:"I10ifHO0PEGrSxI_nNi-ag",route:"/next"},{_id:"_dy3uCTWF0qsWqELiinqFg",route:"/next/thisweek"}]],
//    "/next/soon":[[1],[{_id:"I10ifHO0PEGrSxI_nNi-ag",route:"/next"},{_id:"w7mtxGN6Vkycw0pzuc7nHw",route:"/next/soon"}]],
//    "/focus":[[],[{_id:"fFrT8jnMA0W0iqLa8iLeNw",route:"/focus"}]],
//    "/waitingfor":[[],[{_id:"qvyAi6BwzUefiROWuco38g",route:"/waitingfor"}]],
//    "/waitingfor/:id":[[],[{_id:"qvyAi6BwzUefiROWuco38g",route:"/waitingfor/:id"}]],
//    "/scheduled":[[4],[{_id:"ELm2BGNyHkCGsEzL5hp_JQ",route:"/scheduled"}]],
//    "/scheduled/calendar":[[4],[{_id:"ELm2BGNyHkCGsEzL5hp_JQ",route:"/scheduled"},{_id:"kvIGBCUWZkuzp86JaHye4A",route:"/scheduled/calendar"}]],
//    "/scheduled/reminders":[[4],[{_id:"ELm2BGNyHkCGsEzL5hp_JQ",route:"/scheduled"},{_id:"XueTfO9q9EuzgzsMcjI1oA",route:"/scheduled/reminders"}]],
//    "/someday":[[],[{_id:"Jldp4JOaD0Oa3W1eOe17ug",route:"/someday"}]],
//    "/someday/:id":[[],[{_id:"Jldp4JOaD0Oa3W1eOe17ug",route:"/someday/:id"}]],
//    "/project":[[6],[{_id:"UeWFiTObrEGrl88O9woGtA",route:"/project"}]],
//    "/project/1":[[6],[{_id:"UeWFiTObrEGrl88O9woGtA",route:"/project"},{_id:"7EHOtAYARkG0c43qsDH5cQ",route:"/project/1"}]],
//    "/project/2":[[6],[{_id:"UeWFiTObrEGrl88O9woGtA",route:"/project"},{_id:"0dCP51BWpEuPWDLiWVKQOQ",route:"/project/2"}]],
//    "/project/3":[[6],[{_id:"UeWFiTObrEGrl88O9woGtA",route:"/project"},{_id:"C_xUMSgdpEuS4Yt1XlO-XQ",route:"/project/3"}]],
//    "/project/:id":[[6],[{_id:"UeWFiTObrEGrl88O9woGtA",route:"/project"},{_id:"C_xUMSgdpEuS4Yt1XlO-XQ",route:"/project/:id"}]],
//    "/review":[[],[{_id:"IsYuh58UnkyUYZKU0TcGXw",route:"/review"}]],
//    "/lists":[[8],[{_id:"ZABTfpmKh0KSbeN7QwKd3Q",route:"/lists"}]],
//    "/lists/checklists":[[8],[{_id:"ZABTfpmKh0KSbeN7QwKd3Q",route:"/lists"},{_id:"uP4uSZ3m9U_bDloeUpDcYw",route:"/lists/checklists"}]],
//    "/lists/reference":[[8],[{_id:"ZABTfpmKh0KSbeN7QwKd3Q",route:"/lists"},{_id:"f4NkhuA_PkGyRi7yZIx0Qg",route:"/lists/reference"}]],
//    "/lists/reference/:id":[[8],[{_id:"ZABTfpmKh0KSbeN7QwKd3Q",route:"/lists"},{_id:"f4NkhuA_PkGyRi7yZIx0Qg",route:"/lists/reference/:id"}]],
//    "/lists/done":[[8],[{_id:"ZABTfpmKh0KSbeN7QwKd3Q",route:"/lists"},{_id:"3Jrjgc86U0m6afkizxB2SA",route:"/lists/done"}]],
//    "/lists/done/:id":[[8],[{_id:"ZABTfpmKh0KSbeN7QwKd3Q",route:"/lists"},{_id:"3Jrjgc86U0m6afkizxB2SA",route:"/lists/done/:id"}]],
//    "/lists/trash":[[8],[{_id:"ZABTfpmKh0KSbeN7QwKd3Q",route:"/lists"},{_id:"pSzvcNe3T0q5fwcB2kDUtQ",route:"/lists/trash"}]],
//    "/lists/trash/:id":[[8],[{_id:"ZABTfpmKh0KSbeN7QwKd3Q",route:"/lists"},{_id:"pSzvcNe3T0q5fwcB2kDUtQ",route:"/lists/trash/:id"}]],
//    "/contexts":[[9],[{_id:"TuVm9HPakUeoCI2e7XLXPA",route:"/contexts"}]],
//    "/contexts/roles":[[9],[{_id:"TuVm9HPakUeoCI2e7XLXPA",route:"/contexts"},{_id:"RFhgTTkk0Ey3kg_xSpwD8w",route:"/contexts/roles"}]],
//    "/contexts/contexts":[[9],[{_id:"TuVm9HPakUeoCI2e7XLXPA",route:"/contexts"},{_id:"QXFQzrUDCUC_kfWP9zSPDg",route:"/contexts/contexts"}]],
//    "/contexts/flags":[[9],[{_id:"TuVm9HPakUeoCI2e7XLXPA",route:"/contexts"},{_id:"0w0JGgMyX0e0YWm583VwOQ",route:"/contexts/flags"}]],
//    "/contexts/delegates":[[9],[{_id:"TuVm9HPakUeoCI2e7XLXPA",route:"/contexts"},{_id:"QcRkScJUWkesxZ3Wn-ZT_Q",route:"/contexts/delegates"}]],
//    "/settings":[[10],[{_id:"lMsxrLlF2Eq6PHgxX2_jkw",route:"/settings"}]],
//    "/settings/profile":[[10],[{_id:"lMsxrLlF2Eq6PHgxX2_jkw",route:"/settings"},{_id:"H-IuJIo9Vkif4JZRKqUd-Q",route:"/settings/profile"}]],
//    "/settings/general":[[10],[{_id:"lMsxrLlF2Eq6PHgxX2_jkw",route:"/settings"},{_id:"XcWlwKAXUUS-R-GHN6Ugfg",route:"/settings/general"}]]
//};